USE [master]
GO
/****** Object:  Database [Schools]    Script Date: 18.09.2022 12:18:57 ******/
CREATE DATABASE [Schools]
 CONTAINMENT = NONE
 --ON PRIMARY 
--( NAME = N'Schools', FILENAME = N'F:\projects\Schools\Schools.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
--LOG ON 
--( NAME = N'Schools_log', FILENAME = N'F:\projects\Schools\Schools_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Schools] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Schools].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Schools] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Schools] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Schools] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Schools] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Schools] SET ARITHABORT OFF 
GO
ALTER DATABASE [Schools] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Schools] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Schools] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Schools] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Schools] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Schools] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Schools] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Schools] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Schools] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Schools] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Schools] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Schools] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Schools] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Schools] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Schools] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Schools] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Schools] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Schools] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Schools] SET  MULTI_USER 
GO
ALTER DATABASE [Schools] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Schools] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Schools] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Schools] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Schools] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Schools] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Schools] SET QUERY_STORE = OFF
GO
USE [Schools]
GO
/****** Object:  Table [dbo].[Address]    Script Date: 18.09.2022 12:18:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Address](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Country] [nvarchar](50) NOT NULL,
	[City] [nvarchar](50) NOT NULL,
	[Street] [nvarchar](50) NOT NULL,
	[PostalCode] [int] NOT NULL,
 CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Director]    Script Date: 18.09.2022 12:18:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Director](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Job] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Director] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 18.09.2022 12:18:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Age] [int] NOT NULL,
	[SchoolID] [int] NOT NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Floor]    Script Date: 18.09.2022 12:18:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Floor](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Number] [int] NOT NULL,
	[SchoolID] [int] NOT NULL,
 CONSTRAINT [PK_Floor] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Room]    Script Date: 18.09.2022 12:18:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Room](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Number] [int] NOT NULL,
	[FloorID] [int] NOT NULL,
	[RoomTypeID] [int] NOT NULL,
 CONSTRAINT [PK_Room] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RoomType]    Script Date: 18.09.2022 12:18:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RoomType](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_RoomType] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[School]    Script Date: 18.09.2022 12:18:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[School](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[AddressID] [int] NOT NULL,
	[OpeningDate] [date] NULL,
 CONSTRAINT [PK_School] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SchoolEmployee]    Script Date: 18.09.2022 12:18:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SchoolEmployee](
	[SchoolID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Teacher]    Script Date: 18.09.2022 12:18:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Teacher](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Job] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Teacher] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_School] FOREIGN KEY([SchoolID])
REFERENCES [dbo].[School] ([ID])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_School]
GO
ALTER TABLE [dbo].[Floor]  WITH CHECK ADD  CONSTRAINT [FK_Floor_School] FOREIGN KEY([SchoolID])
REFERENCES [dbo].[School] ([ID])
GO
ALTER TABLE [dbo].[Floor] CHECK CONSTRAINT [FK_Floor_School]
GO
ALTER TABLE [dbo].[Room]  WITH CHECK ADD  CONSTRAINT [FK_Room_Floor] FOREIGN KEY([FloorID])
REFERENCES [dbo].[Floor] ([ID])
GO
ALTER TABLE [dbo].[Room] CHECK CONSTRAINT [FK_Room_Floor]
GO
ALTER TABLE [dbo].[Room]  WITH CHECK ADD  CONSTRAINT [FK_Room_RoomType] FOREIGN KEY([RoomTypeID])
REFERENCES [dbo].[RoomType] ([ID])
GO
ALTER TABLE [dbo].[Room] CHECK CONSTRAINT [FK_Room_RoomType]
GO
ALTER TABLE [dbo].[School]  WITH CHECK ADD  CONSTRAINT [FK_School_Address] FOREIGN KEY([AddressID])
REFERENCES [dbo].[Address] ([ID])
GO
ALTER TABLE [dbo].[School] CHECK CONSTRAINT [FK_School_Address]
GO
ALTER TABLE [dbo].[SchoolEmployee]  WITH CHECK ADD  CONSTRAINT [FK_SchoolEmployee_Employee] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[Employee] ([ID])
GO
ALTER TABLE [dbo].[SchoolEmployee] CHECK CONSTRAINT [FK_SchoolEmployee_Employee]
GO
ALTER TABLE [dbo].[SchoolEmployee]  WITH CHECK ADD  CONSTRAINT [FK_SchoolEmployee_School] FOREIGN KEY([SchoolID])
REFERENCES [dbo].[School] ([ID])
GO
ALTER TABLE [dbo].[SchoolEmployee] CHECK CONSTRAINT [FK_SchoolEmployee_School]
GO
USE [master]
GO
ALTER DATABASE [Schools] SET  READ_WRITE 
GO
